# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_grpc_pb2 as calculator__grpc__pb2


class apiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add = channel.unary_unary(
        '/main.api/add',
        request_serializer=calculator__grpc__pb2.twoNums.SerializeToString,
        response_deserializer=calculator__grpc__pb2.num.FromString,
        )
    self.sub = channel.unary_unary(
        '/main.api/sub',
        request_serializer=calculator__grpc__pb2.twoNums.SerializeToString,
        response_deserializer=calculator__grpc__pb2.num.FromString,
        )
    self.mul = channel.unary_unary(
        '/main.api/mul',
        request_serializer=calculator__grpc__pb2.twoNums.SerializeToString,
        response_deserializer=calculator__grpc__pb2.num.FromString,
        )
    self.div = channel.unary_unary(
        '/main.api/div',
        request_serializer=calculator__grpc__pb2.twoNums.SerializeToString,
        response_deserializer=calculator__grpc__pb2.num.FromString,
        )


class apiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sub(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mul(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def div(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add': grpc.unary_unary_rpc_method_handler(
          servicer.add,
          request_deserializer=calculator__grpc__pb2.twoNums.FromString,
          response_serializer=calculator__grpc__pb2.num.SerializeToString,
      ),
      'sub': grpc.unary_unary_rpc_method_handler(
          servicer.sub,
          request_deserializer=calculator__grpc__pb2.twoNums.FromString,
          response_serializer=calculator__grpc__pb2.num.SerializeToString,
      ),
      'mul': grpc.unary_unary_rpc_method_handler(
          servicer.mul,
          request_deserializer=calculator__grpc__pb2.twoNums.FromString,
          response_serializer=calculator__grpc__pb2.num.SerializeToString,
      ),
      'div': grpc.unary_unary_rpc_method_handler(
          servicer.div,
          request_deserializer=calculator__grpc__pb2.twoNums.FromString,
          response_serializer=calculator__grpc__pb2.num.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.api', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
